### ISSUE TITLE
Cannot find namespace 'ThemeContext'.ts(2503)

### ISSUE THREAD

**Issue by muuvmuuv** [blvdgroup/tslint-config-blvd#3]
Hey, I don't know if this belongs here, but I guess the error has something to do with the TS linter. I copied this code https://www.gatsbyjs.org/blog/2019-01-31-using-react-context-api-with-gatsby/ : `src/context/ThemeContext.js` and got the above error.

**Comment by thetrevorharmon** [comment]
@muuvmuuv did you ever figure this out?

**Comment by muuvmuuv** [comment]
@thetrevorharmon no, and can't remember what the actual problem was, but I guess I just switched to RxJS to handle data sharing between components.

Will close this, as I think it does not really is a problem of this config.

**Comment by thetrevorharmon** [comment]
For anybody seeing this in the future, the problem was that I had it as `ThemeContext.ts` when it needs to be a `.tsx` extension.

**Comment by jonatasoc-old** [comment]
> For anybody seeing this in the future, the problem was that I had it as `ThemeContext.ts` when it needs to be a `.tsx` extension.

Can I like it one thousand times? Thank youuuuuuuuuuu!

**Comment by Raphaelmbewe** [comment]
@thetrevorharmon  thanks I spent too much time debugging this.

**Comment by alexmanzo** [comment]
@thetrevorharmon It's always the simple things...... thank you for this!! Saved me from hours of dread.

**Comment by eulazzo** [comment]
> For anybody seeing this in the future, the problem was that I had it as `ThemeContext.ts` when it needs to be a `.tsx` extension.

Thank you for that tip, i spent a lot of time  debugging this.

**Comment by wangaevans** [comment]
> For anybody seeing this in the future, the problem was that I had it as `ThemeContext.ts` when it needs to be a `.tsx` extension.

OMG! This was stressing me alot,  this fixed the issue.

**Comment by manpikingillz** [comment]
> For anybody seeing this in the future, the problem was that I had it as ThemeContext.ts when it needs to be a .tsx extension.

Thank you. I spent a lot of time debugging this

**Comment by JheyssonD** [comment]
> For anybody seeing this in the future, the problem was that I had it as `ThemeContext.ts` when it needs to be a `.tsx` extension.

thanks this work for me too

**Comment by FereshtehDehghani** [comment]
> For anybody seeing this in the future, the problem was that I had it as `ThemeContext.ts` when it needs to be a `.tsx` extension.
It's great .you made me happy thanks a lot

**Comment by shreyanshxyz** [comment]
> For anybody seeing this in the future, the problem was that I had it as `ThemeContext.ts` when it needs to be a `.tsx` extension.

Thanks a ton! Spent hours trying to debug this haha

**Comment by ninnistic** [comment]
> For anybody seeing this in the future, the problem was that I had it as `ThemeContext.ts` when it needs to be a `.tsx` extension.

Thanks a lot <3

**Comment by hossain45** [comment]
> For anybody seeing this in the future, the problem was that I had it as `ThemeContext.ts` when it needs to be a `.tsx` extension.

dude this one is a lifesaver... thanks man
I spent 3 hours -_-

**Comment by pnutmath** [comment]
@thetrevorharmon you are still saving lifes!

**Comment by ashish-sng** [comment]
damn! thanks alottttt! 🚀

**Comment by ashish-sng** [comment]
> For anybody seeing this in the future, the problem was that I had it as `ThemeContext.ts` when it needs to be a `.tsx` extension.

damn! thanks alotttt! 🚀 😄

**Comment by Asiya1330** [comment]
> For anybody seeing this in the future, the problem was that I had it as `ThemeContext.ts` when it needs to be a `.tsx` extension.

Boooom!..

Thanks.

**Comment by iamlos** [comment]
> For anybody seeing this in the future, the problem was that I had it as `ThemeContext.ts` when it needs to be a `.tsx` extension.

Gemini Code Ai couldn't debug this. Went in circles, two days later...I find this. Thanks!
